# Generated conda environment file
name: template
channels:
- anaconda
- conda-forge
- defaults
dependencies:
- pip:
  - ipympl
  - ipywidgets
  - loguru
  - matplotlib
  - scipy
  - pyserial
  - pandas
  - xarray
  - black
  - flake8
  - ipython
  - nbsphinx
  - numpydoc
  - pre-commit
  - pytest
  - pytest-cov
  - toml
  - sphinx_gallery
  - sphinx_rtd_theme
# note the restart of the alphabetization in pip depenndecies is where dev starts
