name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.9, ]
        # python-version: [3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.1.1
      with:
        activate-environment: dipole-test
        python-version: ${{ matrix.python-version }}

    - name: Install Env
      run: |
        python --version
        conda install -c conda-forge pytest pytest-cov certifi">=2017.4.17" pandoc
        pip install -r requirements-dev.txt

    - name: Install Our Package
      run: |
        pip install -e .
        conda list
        echo "environment contents"
        pip freeze
        
    - name: Install Jupyter and dependencies
      run: |
        pip install jupyter
        pip install ipykernel
        python -m ipykernel install --user --name dipole-test
        # Install any other dependencies you need

    - name: Execute Jupyter Notebooks
      run: |
        # Straight line transect examples
        jupyter nbconvert --to notebook --execute docs/examples/moving_source_transectsweep_1mAm2.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/moving_source_transectsweep_10mAm2.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/moving_source_amplitudesweep.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/moving_source_velocitysweep.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/moving_source_noisy_transect_1m_offset.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/moving_source_noisy_transect_30cm_offset.ipynb

        # Examples similar to the compass pendulum experiments
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_compass/pendulum_ODE.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_compass/singlebollard_pendulum_transectsweep_1mAm2_fremont_b.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_compass/singlebollard_pendulum_transectsweep_1mAm2_fremont_zflip_b.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_compass/singlebollard_pendulum_transectsweep_1mAm2_northpole_b.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_compass/singlebollard_pendulum_transectsweep_1mAm2_northpole_zflip_b.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_compass/singlebollard_pendulum_transectsweep_1mAm2_orlando_b.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_compass/singlebollard_pendulum_transectsweep_1mAm2_orlando_zflip_b.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_compass/singlebollard_pendulum_transectsweep_1mAm2_singapore_b.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_compass/singlebollard_pendulum_transectsweep_1mAm2_singapore_zflip_b.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_compass/Timeseries/Pendulum_1mAm2/pendulum_30cmoffset_inducing_field_variation_zflip.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_compass/Timeseries/Pendulum_1mAm2/pendulum_30cmoffset_inducing_field_variation.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_compass/singlebollard_pendulum_transectsweep_10mAm2_fremont_zflip_b.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_compass/singlebollard_pendulum_transectsweep_10mAm2_fremont_zflip_dbdt.ipynb

        # Examples similar to the small ball bearing pendulum experiments
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_small_ball_bearing/pendulum_ODE_small_ballbearing.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_small_ball_bearing/singlebollard_pendulum_small_ballbearing_transectsweep_fremont_zflip_b.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_small_ball_bearing/singlebollard_pendulum_small_ballbearing_transectsweep_fremont_zflip_dbdt.ipynb
        
        # Examples similar to the large ball bearing pendulum experiments
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_large_ball_bearing/pendulum_ODE_large_ballbearing.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_large_ball_bearing/singlebollard_pendulum_large_ballbearing_transectsweep_fremont_zflip_b.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/pendulum_large_ball_bearing/singlebollard_pendulum_large_ballbearing_transectsweep_fremont_zflip_dbdt.ipynb

        # Straight line transects with 2 bollards (SafePoint system)
        jupyter nbconvert --to notebook --execute docs/examples/safepoint_system_straight_transect_1mAm2.ipynb
        jupyter nbconvert --to notebook --execute docs/examples/safepoint_system_straight_transect_1mAm2_dbdt.ipynb


    - name: Run Tests
      run: |
        # pytest -s -v tests/synthetic/test_fourier_coefficients.py --cov=./ --cov-report=xml --cov=aurora
        pytest -s -v --cov=./ --cov-report=xml --cov=st

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false

#    - name: Build Doc
#      if: ${{ (github.ref == 'refs/heads/main') && (matrix.python-version == '3.8')}}
#      run: |
#        cd docs
#        make html
#        cd ..

#    - name: GitHub Pages
#      if: ${{ (github.ref == 'refs/heads/main') && (matrix.python-version == '3.8')}}
#      uses: crazy-max/ghaction-github-pages@v2.5.0
#      with:
#        build_dir: docs/_build/html
#        # Write the given domain name to the CNAME file
#        # fqdn: aurora.simpeg.xyz
#        # Allow Jekyll to build your site
#        jekyll: false # optional, default is true
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
